# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:         pretty

# Setup
title:            Anthony Nguyen
tagline:          ''
description:      'Anthony Nguyen - Interactive UI & UX Designer'
url:              http://antnguyen.com
baseurl:          '/'
paginate:         5

author:
  name:           'Anthony Nguyen'
  url:            https://twitter.com/atn1988

# Custom vars
version:          1.0.0