# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:         pretty

# Setup
title:            Free People
tagline:          ''
description:      'Free People'
url:              https://rawgit.com/freepeople/styleguide/master/_site/
baseurl:          '/'
paginate:         5

author:
  name:           'Free People'


# Custom vars
version:          1.0.0